version: "3.9"
services:
  basketdb:
    container_name: basketdb
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: basketdb-vol
        target: /data
volumes:
  basketdb-vol: {}