version: '3.4'

services:
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Market.Catalog.Api/Dockerfile
  
  catalogdb:
    image: mongo

volumes:
  mongo_data: