version: '3.4'

services:
  catalog-api:
    image: ${DOCKER_REGISTRY-}marketcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Market.Catalog.Api/Dockerfile

  catalogdb:
    image: mongo

  basket-api:
    image: ${DOCKER_REGISTRY-}marketbasketapi
    build:
      context: .
      dockerfile: Services/Basket/Market.Basket.Api/Dockerfile

  basketdb:
    image: redis

volumes:
  catalog-api-vol:
  catalogdb-vol:
  basket-api-vol:
  basketdb-vol:
