version: '3.4'

services:
  catalog-api:
    image: ${DOCKER_REGISTRY-}marketcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Market.Catalog.Api/Dockerfile

  catalogdb:
    image: mongo

volumes:
  catalog-api-vol:
  catalogdb-vol: