version: '3.4'

services:
  catalog-api:
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=mongodb://rahim373:Me.rahim29@catalogdb:27017
    ports:
      - "5000:80"
    volumes:
      - type: volume
        source: catalog-api-vol
        target: /app

  catalogdb:
    container_name: catalogdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rahim373
      MONGO_INITDB_ROOT_PASSWORD: Me.rahim29
      MONGO_INITDB_DATABASE: CatalogDb
    volumes:
      - type: volume
        source: catalogdb-vol
        target: /data/db
  
  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=basketdb:6379
    ports:
      - "5001:80"
    volumes:
      - type: volume
        source: basket-api-vol
        target: /app

  basketdb:
    container_name: basketdb
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: basketdb-vol
        target: /data